// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7iFi6Bp3lGyJh3ShxHAHsouodELNEhWQ',
    appId: '1:216119213907:web:29c402294eaf67ee2aeba6',
    messagingSenderId: '216119213907',
    projectId: 'news-29ea3',
    authDomain: 'news-29ea3.firebaseapp.com',
    storageBucket: 'news-29ea3.firebasestorage.app',
    measurementId: 'G-M0GH57W2EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu50iBD8Cs_Acc6Yl4OoBhVimadPh8JG8',
    appId: '1:216119213907:android:b83ad14eca2161a22aeba6',
    messagingSenderId: '216119213907',
    projectId: 'news-29ea3',
    storageBucket: 'news-29ea3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGwftIg0FtzBjBIAfsJJ1MLrcuvYqd3n4',
    appId: '1:216119213907:ios:a8fe60425816052b2aeba6',
    messagingSenderId: '216119213907',
    projectId: 'news-29ea3',
    storageBucket: 'news-29ea3.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGwftIg0FtzBjBIAfsJJ1MLrcuvYqd3n4',
    appId: '1:216119213907:ios:a8fe60425816052b2aeba6',
    messagingSenderId: '216119213907',
    projectId: 'news-29ea3',
    storageBucket: 'news-29ea3.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7iFi6Bp3lGyJh3ShxHAHsouodELNEhWQ',
    appId: '1:216119213907:web:05a4e3dd884557f62aeba6',
    messagingSenderId: '216119213907',
    projectId: 'news-29ea3',
    authDomain: 'news-29ea3.firebaseapp.com',
    storageBucket: 'news-29ea3.firebasestorage.app',
    measurementId: 'G-DYX7DM6KQM',
  );
}
